### ISSUE TITLE
Porting to C#

### ISSUE THREAD

**Issue by hatemnsec** [hlldz/Phant0m#6]
Do you have any plans on porting this awesome script to C#, since PowerShell is not opsec safe nowadays.

**Comment by hlldz** [comment]
Hi,

Thank you for your feedback.

Yes, I have a plan about update Phant0m with different languages and
different techniques. It is on my roadmap but I cannot give a date at this
time because of my other projects  priorities.

I always open for the support of you or the community.

Best regards.


18 Haz 2020 Per, saat 03:52 tarihinde Hatem Nasser <notifications@github.com>
şunu yazdı:

**Comment by RubyistCTRLDYT** [comment]
I currently working on a  C# version, but there are some errors I need to fix, anyone could help me?

**Comment by RubyistCTRLDYT** [comment]
@hlldz

**Comment by RubyistCTRLDYT** [comment]
@hatemnsec
